pipeline {
  agent none
  stages {
    stage('First-Script') {
      agent {
        docker { image 'python:3' }
      }
      steps {
        sh 'python --version'
        python3 --version
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
